from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field


# ==========================================
# Company Router Schemas
# ==========================================


class CompanyCreate(BaseModel):
    """
    Schema for company profile creation inputs.
    """

    name: str = Field(..., description="Legal or trade name of the company")
    industry: str = Field(..., description="Industry domain the company operates in")
    size: str = Field(..., description="Number of employees or scale category")
    description: Optional[str] = Field(None, description="Optional brief overview of operations")


class CompanyCreateResponse(BaseModel):
    """
    Response schema after creating a company profile.
    """

    id: str = Field(..., description="Dummy generated company ID")
    message: str = Field(..., description="Action confirmation message")


class CompanyProfileResponse(BaseModel):
    """
    Detailed company profile representation.
    """

    id: str = Field(..., description="Unique company ID")
    name: str = Field(..., description="Name of the company")
    industry: str = Field(..., description="Operating industry")
    size: str = Field(..., description="Company size category")
    description: Optional[str] = Field(None, description="Detailed profile overview")
    created_at: datetime = Field(..., description="Date profile was registered")


class CompanyUpdate(BaseModel):
    """
    Schema for making partial updates to a company profile.
    """

    name: Optional[str] = Field(None, description="Updated name of the company")
    industry: Optional[str] = Field(None, description="Updated industry domain")
    size: Optional[str] = Field(None, description="Updated size scale category")
    description: Optional[str] = Field(None, description="Updated profile overview")


class CompanyUpdateResponse(BaseModel):
    """
    Response schema after updating a company profile.
    """

    status: str = Field(..., description="Confirmation status (e.g. 'success')")


# ==========================================
# Documents Router Schemas
# ==========================================


class DocumentUploadResponse(BaseModel):
    """
    Response returned after uploading a document source.
    """

    document_id: str = Field(..., description="Generated document identifier")
    message: str = Field(..., description="Upload success confirmation")


class DocumentMetadata(BaseModel):
    """
    Metadata representation of an uploaded company document.
    """

    filename: str = Field(..., description="Original name of the uploaded file")
    upload_date: datetime = Field(..., description="Timestamp of upload completion")
    type: str = Field(..., description="Document type category (e.g. PDF, DOCX, CSV)")


# ==========================================
# Decision Router Schemas
# ==========================================


class DecisionCreateRequest(BaseModel):
    """
    Input schema to initiate a new decision assessment.
    """

    company_id: str = Field(..., description="ID of the company requesting analysis")
    question: str = Field(..., description="The core decision query or dilemma to evaluate")


class DecisionInitResponse(BaseModel):
    """
    Immediate response returned after initiating a decision evaluation.
    """

    decision_id: str = Field(..., description="Unique tracker ID for the decision run")
    status: str = Field(..., description="Current status of workflow execution")


class ExpertAnalysis(BaseModel):
    """
    Stub output of a single specialized agent's evaluation.
    """

    agent_name: str = Field(..., description="Specialty domain name of the agent")
    analysis: str = Field(..., description="Evaluation notes generated by the expert")
    recommendation: str = Field(..., description="Key recommendation proposed by the expert")


class DecisionDetailedResponse(BaseModel):
    """
    Full workflow result output showing planning, expert feedback, and final judge decision.
    """

    decision_id: str = Field(..., description="Unique decision run tracker ID")
    planner: List[str] = Field(..., description="List of expert agents consulted during routing")
    experts: List[ExpertAnalysis] = Field(..., description="Array of expert evaluation results")
    recommendation: str = Field(..., description="The final synthesized judge consensus verdict")
    confidence: float = Field(..., description="synthesized confidence score (0.0 to 1.0)")
    next_steps: List[str] = Field(..., description="Actionable checklist items resolved from the decision")
    status: str = Field(..., description="Overall resolution status (e.g. 'completed')")


class DecisionApprovalResponse(BaseModel):
    """
    Response schema returning status update after recommendation review.
    """

    status: str = Field(..., description="Action taken status ('approved' or 'rejected')")
